client_config_backend: settings
client_config:
	client_id: 292323902144-jth298fd8itrh7sl9er1buqdmhtmlrvi.apps.googleusercontent.com
	client_secret: 9T9s1Z1qyXzy7zq923bxp6I-
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
- https://www.googleapis.com/auth/drive.file